version: "3.1"

services:
  leanote:
    image: leanote:latest
    build: .
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./data:/data

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: leanote
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: abc123
    depends_on:
      - leanote
